### PR TITLE
RTL Support

### PR DESCRIPTION
**Pull request by Raika**
Add PR for issue #34 
RTL support by `dir="rtl"` on `html` element

### CODE REVIEW

**Comment by vkeusebio** [comment]
do you have a demo?

**Comment by Raika** [comment]
@vkeusebio  I will add a sample file tonight

**Comment by cjpatoilo** [comment]
[RTL Support #44](https://trello.com/c/zkJGUBH8/71-rtl-support-44)

**Comment by cjpatoilo** [comment]
@Raika do you have a demo?

**Comment by Raika** [comment]
it was 4 years ago. I think milligram changes a lot. and I removed the forked repo.
so sorry

**Comment by cjpatoilo** [comment]
@Raika Anyway, thank you for your special attention to Milligram. 
For now, I will close this issue. Please, feel free to reopen or open a new one.

**Pull request closed without merging**
