### PR TITLE
added meteor package support

### PR DESCRIPTION
**Pull request by NoahVlncrt**
I added a simple package js file to make this package available for meteor projects.

### CODE REVIEW

**Comment by cjpatoilo** [comment]
Thus it will be appointed to your repository. It is better to be the project repository.

**Comment by NoahVlncrt** [comment]
Is this the change you were talking about?

**Comment by cjpatoilo** [comment]
It was not quite what I was thinking. The command continues to contain your username. Would you mind submitting the features on different pull request?

**Comment by vkeusebio** [comment]
Simply changing the name of a meteor package from its definition isn't enough. You have to create a new package, set the new package as a dependency of the old one, and imply the new package in the old one.

http://docs.meteor.com/#/full/pack_api_imply

**Comment by NoahVlncrt** [comment]
I believe this is the change you were thinking of instead of it being noahvlncrt:milligram, you wanted it to be milligram:milligram. If there's anything else I can do let me know.

**Comment by vkeusebio** [comment]
@NoahVlncrt
image

**Comment by vkeusebio** [comment]
@NoahVlncrt since there are currently no way to remove published meteor package, you should hide `noahvlncrt:milligram`

ex.
```sh
meteor admin set-unmigrated noahvlncrt:milligram
```

**Comment by cjpatoilo** [comment]
@vkeusebio There is something wrong. Atmosphere informs the 1.0.6 version. Is this right? The official repository the current version is 1.0.3

**Comment by vkeusebio** [comment]
@cjpatoilo noticed that too but that can be easily changed from the package definition file.

**Comment by NoahVlncrt** [comment]
@cjpatoilo okay I'll change the version and hide the old one.

**Comment by NoahVlncrt** [comment]
Everything should be fixed up. If you need anything else be sure to let me know :)

**Comment by cjpatoilo** [comment]
@NoahVlncrt How do I have control over the account that you created in the atmosphere?

**Comment by NoahVlncrt** [comment]
@cjpatoilo As far as I know there is no way to directly add you as an administrator. I will send you an email with the account info. I'll give it the subject "meteor login info"

**Pull request closed without merging**
