### PR TITLE
Remove the resize option in the textarea

### PR DESCRIPTION
**Pull request by tanrax**
### Description

Remove the resize option in the textarea

### CODE REVIEW

**Comment by mansi142003** [comment]
by using the property resize to none

**Comment by tanrax** [comment]
¿? I don't quite understand the message. (Excuse my English)

**Comment by mansi142003** [comment]
I mean in textarea you can write resize to none for example in css
Textarea{
Resize:none;}

**Comment by tanrax** [comment]
Of course.  Where do we want to go? 😅

**Comment by tanrax** [comment]
I think you're trying to tell me something subtly, but I don't get it

**Pull request closed without merging**
