### PR TITLE
145 - Button appears clicked after clicking it

### PR DESCRIPTION
**Pull request by nathanlogan**
This fixes the bug detailed in issue #145.

### Description

I resolved it by removing the errant pseudo-selector (:focus).

### CODE REVIEW

**Comment by cjpatoilo** [comment]
@nathanlogan I notice that is a specific issue only on Safari browser. In other CSS frameworks like [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L242-L245), [Foundation](https://github.com/zurb/foundation-sites/blob/develop/dist/css/foundation.css#L2655-L2657) has use style for this behavior on the button. For these reasons I'm not sure we should remove this behavior. Let's search for other solutions before making a hasty decision.

Anyway, thanks for working to make Milligram better and I will keep your PR open. 👍

**Comment by alexv** [comment]
I also have this issue in Chrome, changing it to hover only (and maybe adding a different style for pressing) solves the issue.

**Comment by cjpatoilo** [comment]
@nathanlogan @alexv 
I would like to return this discussion. Can you help me find a better way to improve this behavior?

**Comment by cjpatoilo** [comment]
@nathanlogan it's not a bug. It's is the normal button behavior. I explain better in this issue: https://github.com/milligram/milligram/issues/145

Thank you for your contribution. For now, I will close this issue.
Please, feel free to reopen with the right changes or open a new one.

**Pull request closed without merging**
