### PR TITLE
Text align

### PR DESCRIPTION
**Pull request by hedii**
I added 2 useful classes: text-left & text-right.
I use it a lot in my own projects, don't know if it is valuable for milligram...

### CODE REVIEW

**Comment by fredericodietz** [comment]
Hi @hedii, I think `.text-center` would be good too, and maybe it would be better in _Typography.sass instead of _Utility.sass file.

**Comment by hedii** [comment]
@fredericodietz text-xxx is more a utility helper class, that can be applied on typo elements but also on other elements

**Comment by rodrigoddalmeida** [comment]
That's actually very useful! :+1:

**Comment by vkeusebio** [comment]
to be semantic, rather than using `text-`, why not use `push-`?

**Comment by hedii** [comment]
it describes the css property, text-x.
push-x may be confusing with float-x.
text-x is also used in other css frameworks, and easy to remember/understand.

**Comment by cjpatoilo** [comment]
Sorry, but [Milligram](https://github.com/milligram/milligram) should be minimalist and the simplest possible.

**Pull request closed without merging**
