### PR TITLE
Add Sass linting support

### PR DESCRIPTION
**Pull request by jackmcpickle**
This will inforce sass guideline as outlined in the [contributing style guide](https://github.com/milligram/milligram/blob/master/contributing.md#style-guide)

Rules are pull from [sass-lints rules](https://github.com/sasstools/sass-lint/tree/develop/docs/rules)

I have added a grunt task too which will lint the `src` dir and fail on rules that are easily fixed - which should also fail the tests. 

the .sass-lint.yml file works great with sublime-text or atom [sass-linters](https://github.com/sasstools/sass-lint#ide-integration) to aid development in the IDE

I have also updated the current src code to pass the rules.

### CODE REVIEW

**Comment by cjpatoilo** [comment]
Hey @jackmcpickle Good call, but recently I decided to remove support for Grunt and keep the npm scripts: https://github.com/milligram/milligram/blob/master/package.json#L61

We could implement the task `lint` before running the task `sass`:
`"build ": "npm-run-all lint sass autoprefixer banner "`

https://github.com/sasstools/sass-lint#cli-examples

**Comment by jackmcpickle** [comment]
Ok nice. @cjpatoilo updated. 

let me know if you want the dist files pushed too.

**Comment by jackmcpickle** [comment]
sorry @cjpatoilo - merged your PRs now

**Comment by cjpatoilo** [comment]
@jackmcpickle Thank you one more time!

**Pull request merged**
