### PR TITLE
Add support for input file

### PR DESCRIPTION
**Pull request by cjpatoilo**
This Pull Request closes this issue #160 

### Description

- Add support for file input 

### Code sample

- [Codepen](https://codepen.io/cjpatoilo/pen/jOWEojo?editors=1100).

### CODE REVIEW

**Comment by cjpatoilo** [comment]
@marcusasplund please, review this PR 🙏

**Comment by marcusasplund** [comment]
Looking good. Two minor things; in the example you have the class names  ```button input-file```, 
on the label the ```input-file``` is obsolete there and could be removed.
Also, i am not sure that it is totally ARIA-compliant to have duplicate labels with same name. But i am unsure of this, and it probably not a problem at all.
Thx for a nice lib, i use it extensively!

**Comment by cjpatoilo** [comment]
[Release v1.5.0](https://trello.com/c/5htSm5hx/97-release-v150)

**Comment by cjpatoilo** [comment]
@marcusasplund Thank you for your thoughts. 🙏 

By default, I think important shows the file input, and if you want to hide just add `input-file` class.
For now, I will accept this PR and the future I will improve the behavior of this feature.

**Pull request merged**
