### PR TITLE
Support more input form types

### PR DESCRIPTION
**Pull request by mkody**
### Description

Add styling for more `<input>` types.

Added:
- `type="color"`
- `type="date"`
- `type="month"`
- `type="week"`
- `type="datetime"`
- `type="datetime-local"`

I also added them to the `test/index.html` file.

### Code sample

http://codepen.io/MKody/pen/BpNRGQ?editors=1000

### CODE REVIEW

**Comment by shellscape** [comment]
very much needed and a relatively minor addition to the codebase. 👍  from me.

**Comment by szul** [comment]
I just had to add styling for some datetime-local types on an app I've been working on, so this a +1 for me.

**Comment by cjpatoilo** [comment]
Nice call @mkody 

Could you help me think of a better implementation? 

Instead of adding what we will use let input defined for all types and exclude only what does not make sense. What do you think? 

ps: [Sorry for delay](https://github.com/milligram/milligram/issues/187#issuecomment-366103733).

**Comment by mkody** [comment]
Well, I would personally apply the style to all inputs and use `:not()` if needed, but I saw it was inclusive so thought there was as actual good reason behind. (Like people creating custom inputs with their own styles?)

So this could just get shortened to 
```css
input,
textarea,
select {
  /* ... */
}
```

**Pull request merged**
