### PR TITLE
added npm auto-update for cdnjs

### PR DESCRIPTION
**Pull request by vkeusebio**
prepare milligram for [cdnjs](https://github.com/vkeusebio/cdnjs/tree/milligram)

### CODE REVIEW

**Comment by cjpatoilo** [comment]
[Request] Add Milligram [#6579](https://github.com/cdnjs/cdnjs/issues/6579)

**Comment by vkeusebio** [comment]
I'm not really sure but it would be better to have auto-update enabled on the main repository than just the library on cdnjs.

https://github.com/cdnjs/cdnjs/blob/milligram/documents/autoupdate.md

**Comment by PeterDaveHello** [comment]
This section only need to be added on cdnjs's repo.

**Comment by vkeusebio** [comment]
@PeterDaveHello thanks for the clarification, @cjpatoilo I'll close this now.

**Comment by PeterDaveHello** [comment]
Thanks for your help @vkeusebio

**Pull request closed without merging**
