### PR TITLE
Added divider

### PR DESCRIPTION
**Pull request by mirmousaviii**
I added style for divider in _Divider.sass
And I have a question about this commit. After edit changed other style in style.css with "watch" task, is it correct?

### CODE REVIEW

**Comment by cjpatoilo** [comment]
Can you provide a demo page somewhere as jsbin, codepen..?

**Comment by mirmousaviii** [comment]
http://codepen.io/mirmousavi/pen/LGjQyJ
Is it ok?

**Comment by fabienwang** [comment]
It's cool. Thanks @mirmousaviii

**Comment by cjpatoilo** [comment]
@mirmousaviii Thanks for the demo. Great work! I still have some doubts about adding new features based on new classes. Before creating a new feature I always question myself to find a good foundation to validate these ideas.

About the semantic, the function of the element `hr` would not be responsible for the styling of the lines? Add this new module would not leave the focus of the project to keep only the minimum of possible styles?

**Comment by mirmousaviii** [comment]
Dear @cjpatoilo,
Your correct about the semantic, but we can't use `hr` because removed style in [normalized] (https://github.com/necolas/normalize.css/blob/master/normalize.css)

I think we need divider in some project, for example: [Notes] (http://mirmousaviii.github.io/notes/)

If you think the divider is not simple, we can remove other style of divider, for example: divider-dotted, divider-outset and divider-inset.

**Comment by cjpatoilo** [comment]
Sorry it took me so long to respond - missed this somehow. So, I loved the idea of increasing the support other styling elements, you did a awesome job. It was much better with the standard html element but I'm still not sure about adding this new feature. The use of it is quite specific and I can't find arguments to keep it. 

Milligram offers the least possible support to start a project. Note, only the button element has a style of greater support, and this was not an easy decision to make. Create new features will always be a difficult decision to make. I prefer to keep this project the most minimalist and lightweight as possible. 

For now I will close this PR. Thank you for contributing to this project to be the best, it is greatly appreciated.

**Comment by mirmousaviii** [comment]
Ok, That's right, But what do you do when need horizontal rule**?** (`hr` or other divider).
We can not use `hr` because removed style in normalized.

**Comment by cjpatoilo** [comment]
@mirmousaviii The Build organizes the properties in alphabetical order. I needed only update "border-width: 0" so "border: 0". If it were not for you I would not be aware of this problem. Once again, thank you for the incredible attention and also to contribute to this project is the best!

image

**Comment by mirmousaviii** [comment]
@cjpatoilo Thank you

**Pull request closed without merging**
