### PR TITLE
Grid cleanups

### PR DESCRIPTION
**Pull request by jackmcpickle**
Hey, 

had a look through the grid code and thought it could use a bit of tidy up. Let me know your thoughts. 

(Not sure if I'm meant to push built files)

### CODE REVIEW

**Comment by jackmcpickle** [comment]
@bradcliffe Any other issues?

**Comment by bradcliffe** [comment]
Not that I see that are immediately sticking out to me. Looks good. :+1:

**Comment by cjpatoilo** [comment]
Hi @jackmcpickle 
Looking for your PR I found several changes in different parts of which you want to solve. You could send your PR again keeping only the changes to the problem you want to solve / improve? Do not forget the tests and attach the link [Codepen](http://codepen.io/) along with the description.

**Comment by cjpatoilo** [comment]
For now I will close this PR. Anyway thanks for PR.

**Pull request closed without merging**
