### PR TITLE
Fixed #3 - Added SVG caret for select

### LINKED ISSUE #3: Forms: select box is unstyled
The default select styles get removed by ```appearance: none``` but no custom styles are in place.

select

### PR DESCRIPTION
**Pull request by joaobarbosa**
As suggested by @cjpatoilo in the last attempt to fix, I'm not using `appearance: menulist` to avoid default browser rendering and didn't commit the .css files generated by Grunt.

This is the solution I find out to style `<select>` elements and keep the framework without images or external resources.

### CODE REVIEW

**Comment by joaobarbosa** [comment]
I'd like to hear @vkeusebio and @fabienwang opinions too :)

**Comment by fabienwang** [comment]
Can you provide a demo page somewhere?

**Comment by joaobarbosa** [comment]
@fabienwang here: http://joaootavio.com.br/labs/milligram-select-demo/

**Comment by fabienwang** [comment]
I would add:
an hover effect on the select: with a light background like rgba(64,64,64,0.2)
an hover effect on the input , like a lighter border color but it's out of the context

Out of this, it's just fine to me to get the options rendered by the system, because if you want to customize these, it would require custom javascript & more css as well, and it would be heavy

**Comment by cjpatoilo** [comment]
Great Work! Thanks for the PR

**Pull request merged**
