### PR TITLE
give more space to Button to fix #19

### LINKED ISSUE #19: No outline with outlined-button
Hello!
I am here just to say that `.outline-button` selector on example buttons page isn't really outlined:

untitled

But if I zoom-in browser, it's come back:

screen shot 2016-01-08 at 07 55 08

```
Safari Version 9.0.2 (11601.3.9)
OS X 10.11.2
```

### PR DESCRIPTION
**Pull request by vkeusebio**

### CODE REVIEW

**Comment by cjpatoilo** [comment]
Did you make some test? You can provide a demo page somewhere?

**Comment by vkeusebio** [comment]
@cjpatoilo [jsbin](https://jsbin.com/tugazuhipa/edit?output)

**Comment by cjpatoilo** [comment]
What's your OS? I tested on Chrome v47.0.2526.106 (64-bit) of the OS X 10.10.5

This is result:
image

**Comment by vkeusebio** [comment]
Windows 7 32-bit

**Comment by cjpatoilo** [comment]
Thanks, but the problem seems to persist. Closed this PR for now.

**Pull request closed without merging**
